### ISSUE TITLE
Current day will show at the top of the calendar

### ISSUE THREAD

**Issue by penelope-leung** [PenPen812/daily-schedule#1]
# Current day will show at the top of the calendar

## User Story
AS AN employee with a busy schedule
I WANT to add important events to a daily planner
SO THAT I can manage my time effectively

## Acceptance Criteria
GIVEN I am using a daily planner to create a schedule
WHEN I open the planner
THEN the current day is displayed at the top of the calendar

**Comment by PenPen812** [comment]
completed

**Comment by penelope-leung** [comment]
completed
